name: Terraform Workflow

# Déclencheur du workflow : ici, à chaque push sur la branche "main"
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Télécharger le code depuis GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 3 : Installer Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

      # Étape 2 : Connexion à Docker (facultatif si un registre privé est utilisé)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: onlymore
          password: dckr_pat_yG8eEkSOFak_jGT7j_cvZYDvkGk

      - name: Build Docker Image
        run: |
          docker build -t onlymore/esgi-frontend:latest .
        working-directory: PROJET/apps/frontend

      - name: Push Docker Image
        run:  docker push onlymore/esgi-frontend:latest

      - name: Build Docker Image
        run: |
          docker build -t onlymore/esgi-backend:latest .
        working-directory: PROJET/apps/backend

      - name: Push Docker Image
        run:  docker push onlymore/esgi-backend:latest
